version: '3.8'

services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    volumes:
      - ./ingestor:/app/ingestor
    env_file:
      - ./ingestor/.env
    command: python ingestor/new_messages_handler.py

  embedder:
    build:
      context: .
      dockerfile: Dockerfile.embedder
    env_file:
      - ./ingestor/.env
    volumes:
      - ./embedder:/app/embedder
    command: python embedder/main.py