version: '3.8'

services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    volumes:
      - ./ingestor:/app/ingestor
    command: python ingestor/main.py

  embedder:
    build:
      context: .
      dockerfile: Dockerfile.embedder
    volumes:
      - ./embedder:/app/embedder
    command: python embedder/main.py